Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anjali/gn.py", line 77, in <module>
    run_test_and_plot()
  File "/Users/anjali/gn.py", line 73, in run_test_and_plot
    test_optical_train.test_load_lfao()
  File "/Users/anjali/gn.py", line 48, in test_load_lfao
    opt = scopesim.OpticalTrain(cmd)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/utils.py", line 726, in wrapper
    output = func(*args, **kwargs)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/optics/optical_train.py", line 114, in __init__
    self.load(cmds)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/optics/optical_train.py", line 148, in load
    self.update()
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/optics/optical_train.py", line 166, in update
    for hdr in opt_man.image_plane_headers]
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/optics/optics_manager.py", line 197, in image_plane_headers
    raise ValueError("No DetectorList objects found.")
ValueError: No DetectorList objects found.

